version: '3'
services:
  postgres:
    image: postgres:15.4
    restart: always
    environment:
      - POSTGRES_USER=grocery
      - POSTGRES_PASSWORD=grocery
      - POSTGRES_DB=grocery
    ports:
      - "5432:5432"
    volumes:
      - /resources
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d grocery -U grocery" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/grocery
      - spring.datasource.username=grocery
      - spring.datasource.password=grocery
      - spring.jpa.hibernate.ddl-auto=update
    volumes:
      - .m2:/root/.m2